version: '3'

services:
  app:
    image: fizzbuzz
    build: .
    volumes:
      - npm_cache:/root/.npm
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test
    tty: true

volumes:
  npm_cache:
